### ISSUE TITLE
Links for the documentation doesn`t work

### ISSUE THREAD

**Issue by xNok** [moble/jupyter_boilerplate#12]
When clicking on any documentation link it just open another tab with my notebook.

May be it is a template issue because the link has an empty href.

```
<li>
  <a href="#" target="_blank" title="Opens in a new window">
    <i class="fa fa-external-link menu-icon pull-right"></i><span>Documentation</span>
  </a>
</li>
```

**Comment by moble** [comment]
Thanks for pointing this out.  It was an oversight from a recent code refactor.

It won't be in `jupyter_contrib_nbextensions` just yet, though.  @jcb91 Could you remind me of the workflow?

**Comment by jcb91** [comment]
So, now that all the renames have been made in contrib, and no files have been added/removed in this repo, you should be able to do something along the lines of the following:

```bash
# create a new temporary repo to make the update in
git init jbp
cd jbp/

# create a new branch
git checkout -b snippets

# add contrib remote, update our HEAD to point to the current contrib master
git remote add contrib https://github.com/ipython-contrib/jupyter_contrib_nbextensions
git fetch contrib
git merge contrib/master 

# merge updates made in the original boilerplate repo
git remote add boiler https://github.com/moble/jupyter_boilerplate
git fetch boiler
git merge boiler/master
# --- now fix any merge conflicts which arise ---

# push to a new tracked branch in my fork
git remote add jcb91 https://github.com/jcb91/jupyter_contrib_nbextensions
git push --set-upstream jcb91 snippets

# now, make a pull request for the new snippets branch :)
```

**Comment by moble** [comment]
Okay.  I think [I got that](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/917).  Thanks!

**Comment by jcb91** [comment]
looks good to me :smile: :+1:
