### ISSUE TITLE
Scrollable menus?

### ISSUE THREAD

**Issue by boffi** [moble/jupyter_boilerplate#14]
E.g., "SymPy => Functions => Elementary Functions" shows a menu that goes from "Abs" to "Atan2", arrives to the screen's lower border and stops there: no cosine, no exponential, no...

**Comment by moble** [comment]
This works just fine on my Mac in Safari, Chrome, and Firefox; I can just
scroll down when the mouse is over the long menu.  As such, I can't
reproduce the problem, and therefore won't be able to help — though pull
requests are welcome.
