### ISSUE TITLE
Move custom submenu up to postion next to snippets menu item

### ISSUE THREAD

**Issue by MooersLab** [moble/jupyter_boilerplate#18]
By editing the bottom of the custom.js file, I have succeeded in adding a three customized submenu items under the python snippet menu. I now want to promote one customized submenu (my_favorites2) up up to the level of a menu item next to the snippets menu item. I succeeded in doing so with the numpy sub-menu but not with  my_favorites2. I am a javascript beginner. 

```javascript
   snippets_menu.options['menus'] = snippets_menu.default_menus;
    snippets_menu.options['menus'][0]['sub-menu'].push(horizontal_line);
    snippets_menu.options['menus'][0]['sub-menu'].push(my_favorites);
    snippets_menu.options['menus'][0]['sub-menu'].push(my_favorites2);
    snippets_menu.options['menus'][0]['sub-menu'].push(my_favorites3);
    snippets_menu.python.numpy['sub-menu-direction'] = 'left'; // Point new Numpy menus to left
    //snippets_menu.python.my_favorites2['sub-menu-direction'] = 'left'; // Point new Numpy menus to left
    //snippets_menu.options['menus'].push(snippets_menu.default_menus[0]); // Start with the remaining "Snippets" menu
    snippets_menu.options['menus'].push(snippets_menu.python.numpy); // Follow that with a new Numpy menu
    //snippets_menu.options['menus'].push(snippets_menu.python.my_favorites2); // Follow that with a new Numpy menu
    console.log('Loaded `snippets_menu` customizations from `custom.js`');
```

**Comment by moble** [comment]
It looks like the basic problem is that you're adding your custom sub-menu to the `[0]` element of `['menus']`, but if you want it to appear right up there in the menu bar you need to add it *as a new element* of `['menus']`.  So instead of
```javascript
snippets_menu.options['menus'][0]['sub-menu'].push(my_favorites2);
```
try
```javascript
snippets_menu.options['menus'].push(my_favorites2);
```
(In particular, this is what you did with the numpy menu, which is why that worked.)

**Comment by MooersLab** [comment]
Dear moble,

Thank you very much for the clear explanation.
Your suggestion worked like a charm.
Thank you very much!!!

Also, thank you for developing this promising nbextension!

**Comment by moble** [comment]
Glad to help!  :)
