### ISSUE TITLE
installation doens't work with jupyter 4.1.0

### ISSUE THREAD

**Issue by areshytko** [moble/jupyter_boilerplate#9]
I've followed the instructions in README but nothing happened.
Also there are two errors in console log on page load:

require.js?v=6da8be3…:1952 GET http://localhost:8888/nbextensions/jupyter_boilerplate-master.js?v=20161209231031 

utils.js:50 Failed to load extension: ["nbextensions/jupyter_boilerplate-master"] Error: Script error for "nbextensions/jupyter_boilerplate-master"

**Comment by moble** [comment]
Sorry about that.  Jupyter's nbextension conventions change every time I look at them, so I haven't been great about keeping everything up to date.  My hunch is just that you've installed into ipython directories (as my instructions said), but jupyter is no longer using them.  I've updated the installation instructions.  Please try those, and let me know if they work for you.

**Comment by areshytko** [comment]
Still not working, new errors:

http://localhost:8888/nbextensions/boilerplate.js?v=20161214120327 Failed to load resource: the server responded with a status of 404 (Not Found)

Notice that: http://localhost:8888/nbextensions/boilerplate/boilerplate.js?v=2016121412032 - gives the necessary script - browser queries by the wrong address

**Comment by moble** [comment]
Looks like maybe you didn't copy the `require(["nbextensions/boilerplate/boilerplate"]` line correctly.  Did you get both `boilerplate`s?  I tried everything on a fresh install on a brand new virtual machine, and it worked for me...

**Comment by bkandel-edf** [comment]
Hi, do you have instructions to separately install your nbextension? It doesn't appear in the list of nbextensions_configuration in jupyter (4.2.0)

**Comment by moble** [comment]
There've been big changes, since we've been porting it over to the [contributed extensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions); it should be part of the standard collection installation soon.  For now, I think this should work: Clone the repo manually, and enable the extension with

```bash
git clone git://github.com/moble/jupyter_boilerplate
jupyter nbextension install jupyter_boilerplate
jupyter nbextension enable jupyter_boilerplate/main
```

You can then disable the extension if you want with
```bash
jupyter nbextension disable jupyter_boilerplate/main
```
